
//Randomized test cases
`include "/general_tests/base_test.sv"
// `include "/general_tests/read_perm_read_transac_test.sv"

//////////////////////////////////////////////////////////////////////////////////////////////////////
`include "/full_model_tests/full_model_base_test.sv"
//`include "/full_model_tests/rfm_test.sv"

////////////////////////////////////////////////////////////////////////////////////////////////////////

`include "/full_model_tests/full_model_r_perm_read_test.sv"
`include "/full_model_tests/full_model_r_perm_write_test.sv"
`include "/full_model_tests/full_model_no_perm_read_test.sv"
`include "/full_model_tests/full_model_src_no_r_no_perm_read_test.sv"
`include "/full_model_tests/full_model_no_perm_write_test.sv"
`include "/full_model_tests/full_model_NA4_src_rw_no_perm_write.sv"
`include "/full_model_tests/full_model_NA4_rw_perm_write.sv"
`include "/full_model_tests/full_model_NA4_rw_perm_read.sv"
`include "/full_model_tests/full_model_NA4_w_perm_read.sv"
`include "/full_model_tests/full_model_NA4_w_perm_write.sv"
`include "/full_model_tests/full_model_cfg_x_enable.sv"
`include "/full_model_tests/full_model_cfg_x_disable.sv"
`include "/full_model_tests/full_model_src_no_r_cfg_x_disable.sv"
`include "/full_model_tests/full_model_x1_perm_read_chk_x_disable.sv"
`include "/full_model_tests/full_model_x0_perm_read_chk_x_disable.sv"
`include "/full_model_tests/full_model_x_perm_read_no_x_chk_x.sv"
`include "/full_model_tests/full_model_NA4_rw_perm_write_no_w_enable.sv"
`include "/full_model_tests/full_model_NA4_wx_perm_write.sv"
`include "/full_model_tests/full_model_NA4_wx_perm_read.sv"

`include "/full_model_tests/full_model_NA4_illegal_read_interrupt_disable.sv"
`include "/full_model_tests/full_model_NA4_illegal_write_interrupt_disable.sv"
`include "/full_model_tests/full_model_NA4_illegal_instruction_fetch_interrupt_disable.sv"


`include "/full_model_tests/full_model_NA4_illegal_read_interrupt_enable.sv"
`include "/full_model_tests/full_model_NA4_illegal_write_interrupt_enable.sv"
`include "/full_model_tests/full_model_NA4_illegal_instruction_fetch_interrupt_enable.sv"
`include "/full_model_tests/fm_NA4_rd_pri_partial_hit_int_en.sv"
`include "/full_model_tests/fm_NA4_rd_non_pri_partial_hit_int_en.sv"
`include "/full_model_tests/fm_NA4_wr_pri_partial_hit_int_en.sv"
`include "/full_model_tests/fm_NA4_inst_pri_partial_hit_int_en.sv"
`include "/full_model_tests/fm_NA4_wr_non_pri_partial_hit_int_en.sv"
`include "/full_model_tests/fm_NA4_inst_non_pri_partial_hit_int_en.sv"
`include "/full_model_tests/full_model_NA4_illegal_unknown_rrid_interrupt_enable.sv"


`include "/full_model_tests/full_model_NA4_illegal_read_interrupt_enable_io_dis.sv"
`include "/full_model_tests/full_model_NA4_illegal_write_interrupt_enable_io_dis.sv"
`include "/full_model_tests/full_model_NA4_illegal_instruction_fetch_interrupt_enable_io_dis.sv"
`include "/full_model_tests/fm_NA4_rd_pri_partial_hit_int_en_io_dis.sv"
`include "/full_model_tests/fm_NA4_rd_non_pri_partial_hit_int_en_io_dis.sv"
`include "/full_model_tests/full_model_NA4_illegal_unknown_rrid_interrupt_enable_io_dis.sv"

`include "/full_model_tests/full_model_NA4_illegal_read_interrupt_enable_sup.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_msi_interrupt_enable_sup.sv"
`include "/full_model_tests/full_model_NA4_illegal_write_interrupt_enable_sup.sv"
`include "/full_model_tests/full_model_NA4_illegal_write_msi_interrupt_enable_sup.sv"
`include "/full_model_tests/full_model_NA4_illegal_instruction_fetch_interrupt_enable_sup.sv"
`include "/full_model_tests/full_model_NA4_illegal_inst_msi_interrupt_enable_sup.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_msi_interrupt_enable_int_dis.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_interrupt_enable_err_sup.sv"

`include "/full_model_tests/full_model_NA4_illegal_read_interrupt_enable_msi.sv"
`include "/full_model_tests/full_model_NA4_illegal_write_interrupt_enable_msi.sv"
`include "/full_model_tests/full_model_NA4_illegal_instruction_fetch_interrupt_enable_msi.sv"
`include "/full_model_tests/fm_NA4_rd_pri_partial_hit_int_en_msi.sv"
`include "/full_model_tests/fm_NA4_rd_non_pri_partial_hit_int_en_msi.sv"
`include "/full_model_tests/full_model_NA4_illegal_unknown_rrid_interrupt_enable_msi.sv"

`include "/full_model_tests/full_model_NA4_sps_dis_r_perm_read_test.sv"
`include "/full_model_tests/full_model_NA4_dis_chk_x_sps_dis_r_perm_read_test.sv"
`include "/full_model_tests/full_model_NA4_sps_dis_w_perm_write.sv"
`include "/full_model_tests/full_model_NA4_sps_dis_rw_perm_write.sv"
`include "/full_model_tests/full_model_NA4_sps_dis_x_perm_instruction_fetch_test.sv"
`include "/full_model_tests/full_model_NA4_dis_chk_x_sps_dis_x_perm_instr_fetch.sv"

`include "/full_model_tests/fm_NA4_mdlck_read.sv"
`include "/full_model_tests/fm_NA4_mdlck_inst_fetch.sv"
`include "/full_model_tests/fm_NA4_mdlck_write.sv"
`include "/full_model_tests/fm_NA4_mdlckh_read.sv"
`include "/full_model_tests/fm_NA4_mdlckh_inst_fetch.sv"
`include "/full_model_tests/fm_NA4_mdlckh_write.sv"
`include "/full_model_tests/fm_NA4_mdcfglck_read.sv"
`include "/full_model_tests/fm_NA4_mdcfglck_inst_fetch.sv"
`include "/full_model_tests/fm_NA4_mdcfglck_write.sv"
`include "/full_model_tests/fm_NA4_entrylck_read.sv"

`include "/full_model_tests/fm_NA4_source_en.sv"

`include "/full_model_tests/fm_NA4_PP_mdstall.sv"
`include "/full_model_tests/test_ad2_r0_w0_x0_mdstall.sv"
`include "/full_model_tests/test_ad2_r0_w0_x0_mdstall_1.sv"
`include "/full_model_tests/fm_NA4_PP_mdstall_ex.sv"
`include "/full_model_tests/test_ad2_r0_w0_x0_mdstall_exempt.sv"
`include "/full_model_tests/test_ad2_r0_w0_x0_mdstall_exempt_5.sv"
`include "/full_model_tests/test_ad2_r0_w0_x0_mdstall_rrid_reg_5.sv"
`include "/full_model_tests/test_ad2_r0_w0_x0_mdstall_rrid_reg_op.sv"
`include "/full_model_tests/fm_NA4_PP_mdstallh.sv"
`include "/full_model_tests/fm_NA4_PP_mdstallh_ex.sv"
`include "/full_model_tests/fm_NA4_PP_rrid.sv"

`include "/full_model_tests/fm_NA4_prog_prio.sv"

`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_svi_write_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_svw_rrid_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_svw_1_rrid_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_svw_2_rrid_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_svw_3_rrid_test.sv"
`include "/full_model_tests/iopmp_wr_rd_reg_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_multiple_rrid_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_multiple_rrid_read_err_info_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_rrid_read_err_info_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_rrid_read_write_err_info_test.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_unknown_rrid_interrupt_enable_msi.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_interrupt_enable_msi_werr.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_interrupt_enable_msi_werr_wr_err_info.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_en_interrupt_enable_msi_werr_wr_err_info_msi_werr.sv"
`include "/full_model_tests/full_model_NA4_illegal_read_mfr_dis_multi_err_test.sv"


//////////////////////////////////////////////////////////////////////////////////////////////////////////////
//COV
`include "/full_model_tests/full_model_rfm_read_registers_cov.sv"
`include "/full_model_tests/full_model_r_perm_read_illegal_ahb_address_cases.sv"
`include "/full_model_tests/full_model_rfm_entry_array_registers_cov.sv"
`include "/full_model_tests/full_model_ttu_cov.sv"


//////////////////////////////////////////////////////////////////////////////////////////////////////////////

//All Addr Modes
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r0_w1_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad0_r1_w1_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r0_w1_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad1_r1_w1_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r0_w1_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad2_r1_w1_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r0_w1_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w0_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w0_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w0_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w0_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w0_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w0_x1_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w1_x0_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w1_x0_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w1_x0_md0_t2.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w1_x1_md0_t0.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w1_x1_md0_t1.sv"
`include "/general_tests/generated_tests/Addr_Mode/test_ad3_r1_w1_x1_md0_t2.sv"

`include "/general_tests/Directed_Tests/test_ad0_4KB_cross.sv"
`include "/general_tests/Directed_Tests/test_ad1_4KB_cross.sv"
`include "/general_tests/Directed_Tests/test_ad2_4KB_cross.sv"
`include "/general_tests/Directed_Tests/test_ad3_4KB_cross.sv"
`include "/general_tests/Directed_Tests/test_ad1_cross_region.sv"
`include "/general_tests/Directed_Tests/test_ad2_cross_region.sv"
`include "/general_tests/Directed_Tests/test_ad3_cross_region.sv"
`include "/general_tests/Directed_Tests/test_ad2_interpt_sup.sv"
